/*
 -------------------------------------------------------------------------------
 * Name:    BrianFreeman_IS221_Ch4_PP4_12.java
 * Lang:    Java
 * Date:    2021-02-25
 * Author:  Brian Freeman
 * Purpose: This code will randomize an integer between 1-100 when a button is pressed
--------------------------------------------------------------------------------
 * ChangeLog:
 * Who:     Brian Freeman           Date:       2021-02-25
 * Desc:    The button has been created and can randomize an integer
 */
package brianfreeman_is221_ch4_pp4;

// Imports needed functions for main, start, and processButtonPress
import java.util.Random;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.text.Text;
import javafx.scene.control.Button;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;

public class BrianFreeman_IS221_Ch4_PP4_12 extends Application{ 
    
    // Initializes intRandom which is the random number generated by the button
    // randomInterger is the random function which generates the number
    // textRandom is the Text on the Scene that displays the random number
    // These values are declared here to be used in start and processButtonPress
    int intRandom;
    Random randomInteger = new Random();
    Text textRandom;
    
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    
    public void start(Stage stageRandom) {
        
        // Sets textRandom for use in stageRandom
        textRandom = new Text("The random number is: ");
        
        // The button is created and can be pressed
        Button buttonRandom = new Button("Push to Randomize");
        buttonRandom.setOnAction(this::processButtonPress);
        
        // The button is put on the left side of the window with the Text
        // of the random number 40 units away
        // The background color is pink
        FlowPane paneRandom = new FlowPane(buttonRandom, textRandom);
        paneRandom.setAlignment(Pos.CENTER_LEFT);
        paneRandom.setHgap(40);
        paneRandom.setStyle("-fx-background-color: pink");
        
        // Scene sceneRandom is created with the Button usable in it
        Scene sceneRandom = new Scene(paneRandom, 350, 175);
        
        // sceneRandom is added to stageRandom
        stageRandom.setTitle("Random Number Generator");
        stageRandom.setScene(sceneRandom);
        stageRandom.show();
    }    
    // processButtonPress makes clicking buttonRandom display the randomly
    // generated integer
    public void processButtonPress(ActionEvent event){
            
        intRandom = randomInteger.nextInt(100) + 1;
        textRandom.setText("The random number is: " + intRandom);
        
    } 
}
